### ISSUE TITLE
Implement if statement 

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#1]
I want you to implement if condition in code,
Your code should take inpute from user and check in if condition he can register his semester or not,
Hint: take input from user, code will ask user to input his credit houres, if his credit hours is greater then 12 then he can register his semester other wise show him the message that "you have to select at least 12 credit hours"

**Comment by Mehmoodazam107** [comment]
@mhamidjamil dear sir i write our code please check and report

**Comment by mhamidjamil** [comment]
what if user input negative number? also deal with negative number in your code. @Mehmoodazam107

**Comment by Mehmoodazam107** [comment]
@mhamidjamil code has been uploaded please chack again

**Comment by mhamidjamil** [comment]
seems fine.
