### ISSUE TITLE
assignment 2, using any loop.

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#2]
I want you to create new file in same directory name it code3.cpp. 
what to do:
take input from user, say user enter 7
show count down on screen from 7 to **-2**
like this:
7
6
5
4
3
2
1

-1
-2
count down finish, leaving loop.
Remember:
no matter what user enter but i want output to -2 form the number user entered.
@Mehmoodazam107 I want it till tonight.

**Comment by Mehmoodazam107** [comment]
@mhamidjamil sir i have done our assignment please check and report

**Comment by mhamidjamil** [comment]
You code shows like this:
Enter number 5
4
3
2
1
0
-1
-2
But i want it to print like this:
Enter number : 5
4
3
2
1
-1
-2

**Comment by Mehmoodazam107** [comment]
final code uploaded @mhamidjamil
