### ISSUE TITLE
Assignment 4, use loop to print odd number.

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#3]
Create new file and name it **code4.cpp**, write me a code in which code takes input from user and print odd number from user input to zero. For example, user enter 18 your code should print:
`17 15 13 11 9 7 5 3 1.`
Code should print all odd values till 1 and after printing 1 it should also print `.` and this dot should print just after the last odd number which is 1 in our case. `Remember there is no whitespace between last odd number and 1` and sequence should be same don't jump to next line until you print all the odd numbers on one line.
@Mehmoodazam107 this is assignment 4.1 it has 3 parts other 2 parts will be assigned as soon as you done your assigned task and you have to complete these 3 tasks in two days. You can use any type of loop in **4.1** task **but remember** once you use a specific loop you can't use that loop in coming parts **4.2** and **4.3**

- If you have any query just mention me and ask question

**Comment by mhamidjamil** [comment]
@Mehmoodazam107 any update on issue, either it will be solved by the end of today?

**Comment by Mehmoodazam107** [comment]
@mhamidjamil  i have done my assignment please chack and report

**Comment by mhamidjamil** [comment]
let me check @Mehmoodazam107

**Comment by mhamidjamil** [comment]
all the requirements are not satisfied yet, take time and complete all the required points.

**Comment by mhamidjamil** [comment]
@Mehmoodazam107 you can close the issue now

**Comment by Mehmoodazam107** [comment]
ok
