### ISSUE TITLE
assignment 4.2

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#4]
Create new file name it code4_2.cpp and write a code which take two inputs from user and print odd number from highest input value entered by user input to the lowest value user enter. For example, user enter 15 first and then enter 5 your code should print:
`15 13 11 9 7 5.`
or if user enter 2 first and then 13 then output will be:
`13 11 9 7 5 3`

 **Remember:** 
- If user entered small number 1st, then you don't have to print `.` at the end as mentioned.
- no matter user enter small number or large number first output should be from large number to smaller one.

**Comment by mhamidjamil** [comment]
when will you complete the assignment @Mehmoodazam107 ? and is it clear to you?

**Comment by mhamidjamil** [comment]
any update of assignment? @Mehmoodazam107

**Comment by Mehmoodazam107** [comment]
assignment done @mhamidjamil
