### ISSUE TITLE
final assignment

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#5]
Create a new file in the same directory and name it `a4f.cpp`, 

> What you have to do? 
Step 1:

Write me a code in which terminal as user to input two numbers, say user input 2 and 30 divide the higher number from lower number and save the _result_ in a variable in our case it is 15, then divide it again and again until the _result_ becomes less than 10.

> Step 2: 

then print the difference of the result from higher number user enter to the lower number.
`(do step one show the result then the step 2 will be explained in detail)`

**Comment by Mehmoodazam107** [comment]
@mhamidjamil sir i have done my assignment

**Comment by Mehmoodazam107** [comment]
New assignment ?

**Comment by mhamidjamil** [comment]
Assigned, please check @Mehmoodazam107
