### ISSUE TITLE
Last assignment for loops

### ISSUE THREAD

**Issue by mhamidjamil** [Mehmoodazam107/Second-Code#6]
Create a file and name it lft.cpp:
Write me a code in which the user enter two numbers which will be sorted into small and large variable as you learned in previous videos, and after arranging small and large number use while loop to print all those numbers from greater number to smaller number which are dividable from 5 and 3 but not with 2.
@Mehmoodazam107

**Comment by Mehmoodazam107** [comment]
@mhamidjamil done

**Comment by mhamidjamil** [comment]
Don't close the issue untill I approve your assignment and ask you to close @Mehmoodazam107
